#pragma once

#define IDS_CONTEXT_MENU 1

#define IDS_CONVERTCOMMAND_PROGRESSDIALOG_TEXT 10
#define IDS_CONVERTCOMMAND_ASK_REPLACE_TEXT 11
#define IDS_CONVERTCOMMAND_ASK_REPLACE_TITLE 12
#define IDS_CONVERTCOMMAND_ERROR_TEXT 13
