name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build-windows-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build all
        run: |
          ./build_msvc.bat
      - name: package all
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          ./package.bat
      - uses: actions/upload-artifact@v2
        with:
            name: build-windows
            path: |
              rawtojpg-setup.msi
              *.pdb
              RAWtoJPG.dll

  makerelease:
    runs-on: ubuntu-latest
    needs: [build-windows-msvc]
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Download artifact windows
        if: startsWith( steps.tagName.outputs.tag, 'v')
        uses: actions/download-artifact@v2
        with:
          name: build-windows
      - name: Create Release
        if: startsWith( steps.tagName.outputs.tag, 'v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: Release ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: true
      - name: Upload Release Asset windows
        if: startsWith( steps.tagName.outputs.tag, 'v')
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rawtojpg-setup.msi
          asset_name: rawtojpg-setup{{ github.run_id }}.msi
          asset_content_type: application/zip